owner: rvosmik
repo: watchfox-status

sites:
  - name: Watchfox App (UI)
    url: https://app.watchfox.io/

  # Uptime regions (core)
  - name: Ops Uptime EU-Central
    url: https://ops-eu-central.watchfox.io/healthz
  - name: Ops Uptime EU-West
    url: https://ops-eu-west.watchfox.io/healthz
  - name: Ops Uptime US-East
    url: https://ops-us-east.watchfox.io/healthz

  # Bonus / infra helpers (ty co jste teď přidali)
  - name: Ops Domain Checker
    url: https://ops-domain.watchfox.io/healthz
  - name: Ops Heartbeat Checker
    url: https://ops-heartbeat.watchfox.io/healthz

# (volitelně později, až bude /healthz i tam)
#  - name: Ops TLS Checker
#    url: https://ops-tls.watchfox.io/healthz
#  - name: Ops Sitemap
#    url: https://ops-sitemap.watchfox.io/healthz

status-website:
  cname: status.watchfox.io
  name: Watchfox Status
  introTitle: "Watchfox service status"
  introMessage: "Live uptime and incident history."
  navbar:
    - title: Status
      href: /
    - title: App
      href: https://app.watchfox.io/

